name = "tulsi-smarika-admin"
main = "admin-worker.js"
compatibility_date = "2024-09-01"

# KV namespace binding
[[kv_namespaces]]
binding = "RSVP_KV"
preview_id = "e4bd9b5269cb461ca2f4ec0caacc085d"
id = "36be1b6faa594f4ca8789a1000f1f493"

# Environment variables (optional)
[vars]
ENVIRONMENT = "production"

# Route configuration for admin interface
[[routes]]
pattern = "tulsiwedssmarika.com/admin/*"
zone_name = "tulsiwedssmarika.com"